version: '3.8'

services:
    # HTTP Server
    webserver:
        image: 'nginx:alpine'
        container_name: 'stat-webserver'
        restart: unless-stopped
        tty: true
        ports:
            - '127.0.0.1:${APP_PORT:-80}:80'
        volumes:
            - './:/var/www/stat-app'
            - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
            - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
        networks:
            - main
        links:
            - app
        depends_on:
            - app

    # Main Application
    app:
        image: 'stat/app'
        container_name: 'stat-app'
        restart: unless-stopped
        build:
            context: './docker/php'
            dockerfile: 'Dockerfile'
            args:
                UID: '${UID:-1000}'
                GID: '${GID:-1000}'
        working_dir: '/var/www/stat-app'
        volumes:
            - './docker/php/php.ini:/opt/bitnami/php/etc/php.ini'
            - './docker/php/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf'
            - './:/var/www/stat-app'
        networks:
            - main
        depends_on:
            - mariadb
            - redis

    # Worker
    supervisor:
        image: 'stat/app'
        container_name: 'stat-supervisor'
        restart: unless-stopped
        working_dir: '/var/www/stat-app'
        command: 'supervisord -c /supervisord.conf'
        ports:
            - '127.0.0.1:9001:9001'
        volumes:
            - './docker/php/php.ini:/opt/bitnami/php/etc/php.ini'
            - './docker/php/supervisord.conf:/supervisord.conf'
            - './:/var/www/stat-app'
        networks:
            - main
        depends_on:
            - mariadb
            - redis
            - app

    # Database
    mariadb:
        image: 'mariadb:10'
        container_name: 'stat-db'
        restart: unless-stopped
        ports:
            - '127.0.0.1:${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - '${PWD}/data/mariadb:/var/lib/mysql'
        networks:
            - main
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    # Cache
    redis:
        image: 'redis:alpine'
        container_name: 'stat-redis'
        restart: unless-stopped
        command: 'redis-server --requirepass ${REDIS_PASSWORD}'
        ports:
            - '127.0.0.1:${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - '${PWD}/data/redis:/data'
        networks:
            - main
        healthcheck:
            test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
            retries: 3
            timeout: 5s

networks:
    main:
        driver: bridge
        name: stat_main_network
